package com.co.iuvity.kafaka.service;

public class tetsas {

	
	public static void main(String[] args) {
		
		
		String data = "{\r\n"
				+ "    \"kardex\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"name\": \"camisetas\",\r\n"
				+ "            \"inventario\": 10,\r\n"
				+ "            \"ingresos\": [\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 1,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:27:12 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 1,\r\n"
				+ "                        \"name\": \"camisetas\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"10\",\r\n"
				+ "                    \"purchasePrice\": \"900\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 2,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:27:28 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 1,\r\n"
				+ "                        \"name\": \"camisetas\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"5\",\r\n"
				+ "                    \"purchasePrice\": \"920\"\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"egresos\": [\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 5,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:30:24 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 1,\r\n"
				+ "                        \"name\": \"camisetas\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"5\",\r\n"
				+ "                    \"salePrice\": \"800\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 2,\r\n"
				+ "            \"name\": \"vasos\",\r\n"
				+ "            \"inventario\": 3,\r\n"
				+ "            \"ingresos\": [\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 3,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:28:08 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 2,\r\n"
				+ "                        \"name\": \"vasos\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"5\",\r\n"
				+ "                    \"purchasePrice\": \"920\"\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"egresos\": [\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 3,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:28:18 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 2,\r\n"
				+ "                        \"name\": \"vasos\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"1\",\r\n"
				+ "                    \"salePrice\": \"1500\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"id\": 4,\r\n"
				+ "                    \"date\": \"Wed, 14 Aug 2024 16:29:30 GMT\",\r\n"
				+ "                    \"product\": {\r\n"
				+ "                        \"id\": 2,\r\n"
				+ "                        \"name\": \"vasos\"\r\n"
				+ "                    },\r\n"
				+ "                    \"amount\": \"1\",\r\n"
				+ "                    \"salePrice\": \"1500\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		
		
		
		new JsonToCsvTrasformer().jsonToCsv("s", data);
		
		
	}
}
